### ISSUE TITLE
Header Component

### ISSUE THREAD

**Issue by tobiaswild** [Chri1899/dashboard#3]
Primary styling

**Comment by tobiaswild** [comment]
![](https://user-images.githubusercontent.com/46871747/189597780-ddfcf7f0-56f3-453a-a5ac-82a96d200d9a.png)

**Comment by tobiaswild** [comment]
![](https://user-images.githubusercontent.com/46871747/189616277-444c349d-c10e-4dc0-9810-6723de68cf36.png)
Commit: [74bc9c6](https://github.com/Chri1899/dashboard/commit/74bc9c6cbc55c89e96141e8b1634182f5b0b921a)

**Comment by tobiaswild** [comment]
![](https://user-images.githubusercontent.com/46871747/189622253-18c637bb-2b0c-43ea-ae34-57637cd5f177.png)

Commit: [8f0c404](https://github.com/Chri1899/dashboard/commit/8f0c40440308e4e8f614cb8cf8a4e5bf9c5d692c)

**Comment by tobiaswild** [comment]
@Chri1899 Ideas and feedback are now wanted 😄

**Comment by Chri1899** [comment]
> @Chri1899 Ideas and feedback are now wanted 😄

Looks quite nice :D

**Comment by tobiaswild** [comment]
![](https://user-images.githubusercontent.com/46871747/189648097-92bad0fd-8f3d-4456-ad78-76467282935e.png)
bigger icons

Commit: [133c7b4](https://github.com/Chri1899/dashboard/commit/133c7b477e7cc374ac6262bfa83b8b0816026869)

**Comment by tobiaswild** [comment]
![](https://user-images.githubusercontent.com/46871747/189697675-1583ad72-f408-49d3-af9d-81c91d01233c.png)

Sonst noch was? @Chri1899

**Comment by Chri1899** [comment]
> ![](https://user-images.githubusercontent.com/46871747/189697675-1583ad72-f408-49d3-af9d-81c91d01233c.png)
> 
> Sonst noch was? @Chri1899 

Denke für den Anfang ist es schon mehr als in Ordnung, was anderes würde mir nicht einfallen momentan.
