### ISSUE TITLE
Progress-Chart implementation

### ISSUE THREAD

**Issue by Chri1899** [Chri1899/dashboard#6]
Progress-Chart needs to be implementated.

Example picture:

![Screenshot 2022-09-14 at 10 03 50](https://user-images.githubusercontent.com/97324676/190097115-f51a5141-cdb3-4c11-8a88-3b1b5ea42152.png)

**Comment by tobiaswild** [comment]
![](https://user-images.githubusercontent.com/46871747/190394913-1327aa06-969d-45e1-85c9-fbbbc5ea465f.png)

**Comment by Chri1899** [comment]
> ![](https://user-images.githubusercontent.com/46871747/190394913-1327aa06-969d-45e1-85c9-fbbbc5ea465f.png)

Looks nice, can't imagin if the blue fits into the theme, but we can adjust it if possible.

**Comment by tobiaswild** [comment]
ja können wir später machen mit der farbe
